name: build_test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
   job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: |
          sudo apt-get -y update
          sudo apt-get -y install gcc
          sudo apt-get -y install make
          make
